### ISSUE TITLE
convert _itol_metadata.py script to a qemistree  module

### ISSUE THREAD

**Issue by anupriyatripathi** [biocore/q2-qemistree#100]
This is extremely vital -- it will enable us to deploy the tree-rendering capabilities of Qemistree into the GNPS workflow. @qiyunzhu would you be willing to tackle this?

**Comment by qiyunzhu** [comment]
@anupriyatripathi Sure! Won't be too soon though... Please remind me again on Wednesday (via email) and expect my first update on Monday.
