### ISSUE TITLE
Adding a "enhance with Qemistree" to FBMN workflow

### ISSUE THREAD

**Issue by DeepaAcharya** [biocore/q2-qemistree#102]
Similar to other tools like dereplicator etc, this can directly pull the files it needs to run Qemistree with the exception of the SIRIUS file which can be user input

**Comment by anupriyatripathi** [comment]
Hey @DeepaAcharya could you make this issue here: https://github.com/CCMS-UCSD/GNPS_Workflows/issues. It would fall on the GNPS side of things.
