### ISSUE TITLE
iTOL API requires key

### ISSUE THREAD

**Issue by askerdb** [biocore/q2-qemistree#138]
Hey,

I am trying to generate some plots, but it failed on GNPS  (https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=8f979fd9290a4cf8a502a8f7e175fec0)

I downloaded the data and attempted to plot it with my local version of qiime2 but I recieve the following error (full output below):
Plugin error from qemistree:

  ERR 0: Please provide your iTOL API key (APIkey parameter). Anonymous batch upload is not available, please check https://itol.embl.de/infoReg.cgi

Debug info has been saved to /var/folders/kg/0g2167hj1m3fyhh4ng5vz7q03xf1lj/T/qiime2-q2cli-err-rs3gb19w.log

I have an account on iTOL, is there anywhere to enter the information into qemistree?

Full error:

(qiime2-2020.8) chs962@SUND32925:~/Downloads/ProteoSAFe-QEMISTREE-8f979fd9-download_data$ cat /var/folders/kg/0g2167hj1m3fyhh4ng5vz7q03xf1lj/T/qiime2-q2cli-err-rs3gb19w.log
/Users/chs962/anaconda3/envs/qiime2-2020.8/lib/python3.6/site-packages/q2_qemistree/_plot.py:36: UserWarning: The mapping between colors and categories is not unique, some colors have been repeated
  UserWarning)
Traceback (most recent call last):
  File "/Users/chs962/anaconda3/envs/qiime2-2020.8/lib/python3.6/site-packages/q2cli/commands.py", line 329, in __call__
    results = action(**arguments)
  File "<decorator-gen-230>", line 2, in plot
  File "/Users/chs962/anaconda3/envs/qiime2-2020.8/lib/python3.6/site-packages/qiime2/sdk/action.py", line 245, in bound_callable
    output_types, provenance)
  File "/Users/chs962/anaconda3/envs/qiime2-2020.8/lib/python3.6/site-packages/qiime2/sdk/action.py", line 452, in _callable_executor_
    ret_val = self._callable(output_dir=temp_dir, **view_args)
  File "/Users/chs962/anaconda3/envs/qiime2-2020.8/lib/python3.6/site-packages/q2_qemistree/_plot.py", line 203, in plot
    raise ValueError(itol_uploader.comm.upload_output)
ValueError: ERR 0: Please provide your iTOL API key (APIkey parameter). Anonymous batch upload is not available, please check https://itol.embl.de/infoReg.cgi

**Comment by ElDeveloper** [comment]
At this point it will be easier to generate plots using empress. Installation instructions and tutorial here:
https://github.com/biocore/empress

You can input the qemistree, feature table, mapping file and annotations to `qiime empress community-plot`. This will interactively allow you to visualize the data.

We need to update the tutorial here to remove the plotting functionality.

**Comment by ElDeveloper** [comment]
Closing this since https://github.com/CCMS-UCSD/GNPS_Workflows/pull/633 got merged.

**Comment by anupriyatripathi** [comment]
🎉 Thanks!!

Anupriya Tripathi
