### ISSUE TITLE
running the demo pipeline

### ISSUE THREAD

**Issue by MuBulut** [biocore/q2-qemistree#151]
Hi there,
I wanted to run the demo, to check if everything is running well on our servers.
I got to the last point, however I could not find the sample meta file:
 --m-sample-metadata-file path-to-sample-metadata.tsv \
is it possible to upload it for download.

Thanks in advance.
Mustafa

**Comment by MuBulut** [comment]
I would highly appreciate if someone could forward me the sample meta data, since I would love to perform qemistree.

**Comment by ElDeveloper** [comment]
@MuBulut, that file doesn't exist. I understand the tutorial is a bit misleading. The specific command where this file is mentioned is the `q2-empress` command. If you want to  get more information about empress I suggest reading the tutorial here:

https://github.com/biocore/empress

The "sample-metadata-file" files follow QIIME2's metadata guidelines:
https://docs.qiime2.org/2022.2/tutorials/metadata/

Here's an example:
https://data.qiime2.org/2022.2/tutorials/moving-pictures/sample_metadata.tsv

Hope this helps, if not feel free to reopen the issue. Thanks so much for your patience.
